### PR TITLE
Issue #10

### PR DESCRIPTION
**Pull request by geekypandey**
Completed :
1.Removing database code(now in database.py) out of the main code(web_crawler.py)
2.Created a configuration file for mysql database(config.ini)

Pending:
1.The multiprocessing task which has been previously done.(Not able to get it running)

### CODE REVIEW

**Comment by sinha-debojyoti** [comment]
The branch has conflicts. Please try to resolve it.

**Comment by geekypandey** [comment]
Resolved the conflict. Please review the changes again.

**Comment by sinha-debojyoti** [comment]
Is there any issue in pooling.

**Comment by geekypandey** [comment]
I tried integrating it with the changes I made, but I was unable to get it to work . I am new to it , so I have to do the reading.

**Pull request merged**
